<?php require __DIR__.'/auth.php'; require __DIR__.'/branding.php'; $signedIn = retailSignedIn(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NextGen Everyday — Discover your next</title><link rel="stylesheet" href="./assets/site.css"><link rel="stylesheet" href="./assets/shop-interface.css?v=1"><script defer src="./assets/lottie.min.js"></script><script defer src="./assets/motion.js"></script><script type="module" src="./app.js"></script></head><body data-signed-in="<?= $signedIn ? 'true' : 'false' ?>">
<header class="topbar"><div class="wrap nav"><a class="brand" href="/"><img src="<?= brandEscape('logoUrl') ?>" alt="<?= brandEscape('storeName') ?>" class="brand-logo"><small>TECHNOLOGY · PNG</small></a><nav class="nav-links" aria-label="Main navigation"><a href="/">Home</a><a href="/b2c-preview/#catalogue">Shop</a><a href="https://store.nextgenpng.net/">Business store</a><?php if (retailSignedIn()): ?><button class="motion-button" id="cart-open" type="button">Basket <span id="cart-count">0</span></button><form method="post" action="/b2c-preview/logout.php"><input type="hidden" name="csrf" value="<?= retailEscape($_SESSION['csrf']) ?>"><button class="pill" type="submit">Sign out</button></form><?php else: ?><a class="pill" href="/b2c-preview/login.php">Sign in</a><a href="/b2c-preview/register.php">Create account</a><?php endif; ?></nav></div></header>
<main class="wrap"><section class="shop-banner"><div class="hero-copy"><span class="eyebrow">Technology for your everyday</span><h1>Computers, printers & supplies.</h1><p>Browse the range. Create an account to read specifications and use shopping tools.</p><?php if (!$signedIn): ?><a class="button lime" href="./register.php">Create a retail account</a><?php else: ?><span class="pill">Welcome to your retail catalogue</span><?php endif; ?></div><div class="scene"><div class="fallback-art" aria-hidden="true">▣</div><div data-lottie="./assets/retail.json" aria-hidden="true"></div></div></section>
<?php if (!$signedIn): ?><div class="lock-note"><span>⌑ View product names and prices below. Create an account or sign in for details.</span><a class="text-link" href="./login.php">Sign in ↗</a></div><?php endif; ?>

<section id="catalogue"><div class="section-heading"><div><span class="eyebrow">Retail catalogue</span><h2>Browse our products</h2></div></div>
<?php if ($signedIn): ?><form id="search"><label for="keyword">Find a product</label><div class="search-row"><input id="keyword" maxlength="100" placeholder="Search the retail catalogue"><select id="sort" aria-label="Sort products"><option value="0">Recommended</option><option value="1">Newest</option><option value="3">Price: low to high</option><option value="4">Price: high to low</option></select><button class="button">Search</button></div></form><?php endif; ?>
<p id="status" role="status" aria-live="polite">Loading products…</p><div id="products" class="products"></div><?php if ($signedIn): ?><div class="pagination"><button id="previous" type="button">Previous</button><span id="page">Page 1</span><button id="next" type="button">Next</button></div><?php endif; ?></section>
<div class="trust"><span>Based in Papua New Guinea</span><span>Your dedicated everyday store</span><span>Secure retail access</span></div></main>
<?php if ($signedIn): ?><dialog id="detail"><button class="close" type="button" aria-label="Close product">Close</button><div id="detail-content"></div></dialog><dialog id="basket"><button class="close" type="button" aria-label="Close basket">Close</button><h2>Test basket</h2><p>No order is submitted. This basket is held only for this page session.</p><div id="basket-items"></div><button id="clear-basket" type="button">Clear basket</button><a href="https://store.nextgenpng.net/contact">Contact NextGen</a></dialog><?php endif; ?>
<footer class="wrap footer"><img src="<?= brandEscape('logoUrl') ?>" alt="<?= brandEscape('storeName') ?>" class="footer-logo"><span>© <?= date('Y') ?> <?= brandEscape('footerText') ?></span><div><?php if ($retailBranding['contactEmail']): ?><a href="mailto:<?= brandEscape('contactEmail') ?>"><?= brandEscape('contactEmail') ?></a><?php endif; ?><?php if ($retailBranding['contactPhone']): ?><span><?= brandEscape('contactPhone') ?></span><?php endif; ?><a href="https://store.nextgenpng.net/contact">Contact</a><a href="https://store.nextgenpng.net/privacy">Privacy</a><button class="motion-button" data-motion-toggle type="button">Pause animations</button></div></footer></body></html>
